[project]
name = "Itomori"
version = "1.0.0"
description = "TUI Note Writing Tool"
readme = "README.md"
requires-python = ">=3.14"
author = [
    { name = "Ahum Maitra", email = "theahummaitra@gmail.com" }
]
dependencies = [
    "textual[syntax]>=6.6.0",
    "textual-dev>=1.8.0",
    "black>=25.11.0",
]
license = "License.md"
